const BOARD_TYPES = {
    BOARDS_CREATE_START: "BOARDS_CREATE_START",
    BOARDS_CREATE_SUCCESS: "BOARDS_CREATE_SUCCESS",
    BOARDS_CREATE_ERROR: "BOARDS_CREATE_ERROR",

    BOARDS_EDIT_START: "BOARDS_EDIT_START",
    BOARDS_EDIT_SUCCESS: "BOARDS_EDIT_SUCCESS",
    BOARDS_EDIT_ERROR: "BOARDS_EDIT_ERROR",

    BOARDS_DELETE_START: "BOARDS_DELETE_START",
    BOARDS_DELETE_SUCCESS: "BOARDS_DELETE_SUCCESS",
    BOARDS_DELETE_ERROR: "BOARDS_DELETE_ERROR",

    BOARDS_FETCH_ALL_START: "BOARDS_FETCH_ALL_START",
    BOARDS_FETCH_ALL_SUCCESS: "BOARDS_FETCH_ALL_SUCCESS",
    BOARDS_FETCH_ALL_ERROR: "BOARDS_FETCH_ALL_ERROR",

    BOARDS_FETCH_ONE_START: "BOARDS_FETCH_ONE_START",
    BOARDS_FETCH_ONE_SUCCESS: "BOARDS_FETCH_ONE_SUCCESS",
    BOARDS_FETCH_ONE_ERROR: "BOARDS_FETCH_ONE_ERROR",
}

export default BOARD_TYPES