const PEOPLE_TYPES = {
    PEOPLE_CREATE_START: "PEOPLE_CREATE_START",
    PEOPLE_CREATE_SUCCESS: "PEOPLE_CREATE_SUCCESS",
    PEOPLE_CREATE_ERROR: "PEOPLE_CREATE_ERROR",

    PEOPLE_DELETE_START: "PEOPLE_DELETE_START",
    PEOPLE_DELETE_SUCCESS: "PEOPLE_DELETE_SUCCESS",
    PEOPLE_DELETE_ERROR: "PEOPLE_DELETE_ERROR",

    PEOPLE_UPDATE_START: "PEOPLE_UPDATE_START",
    PEOPLE_UPDATE_SUCCESS: "PEOPLE_UPDATE_SUCCESS",
    PEOPLE_UPDATE_ERROR: "PEOPLE_UPDATE_ERROR",

    PEOPLE_FETCH_ALL_START: "PEOPLE_FETCH_ALL_START",
    PEOPLE_FETCH_ALL_SUCCESS: "PEOPLE_FETCH_ALL_SUCCESS",
    PEOPLE_FETCH_ALL_ERROR: "PEOPLE_FETCH_ALL_ERROR",

    PEOPLE_FETCH_START: "PEOPLE_FETCH_START",
    PEOPLE_FETCH_SUCCESS: "PEOPLE_FETCH_SUCCESS",
    PEOPLE_FETCH_ERROR: "PEOPLE_FETCH_ERROR",
}

export default PEOPLE_TYPES;