export default {
    LOGIN_USER_PENDING: "LOGIN_USER_PENDING",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
    REGISTER_USER_PENDING: "REGISTER_USER_PENDING",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_ERROR: "REGISTER_USER_ERROR",
    LOGOUT_USER: "LOGOUT_USER",
}